"""Metrics for data extraction."""

from dataclasses import dataclass, field
from typing import Any

from wukong_engine.core.extraction.elements.values import ExtractionStatus, JobStatus


# Helpers
def _safe_int(value: Any) -> int | None:
    """Safely convert a value to an integer, returning None if conversion fails."""
    try:
        return int(value)
    except ValueError, TypeError:
        return None


@dataclass(frozen=True)
class JobDurationMetrics:
    """Relevant job duration metrics, in milliseconds."""

    avg: int
    min: int
    max: int


@dataclass(frozen=True)
class TokenUsageMetrics:
    """Relevant token usage metrics for LLM interactions."""

    input_tokens: int | None = None  # Input tokens, excluding cached tokens if applicable
    cached_tokens: int | None = None  # Input tokens that used prefix caching
    output_tokens: int | None = None  # Output tokens generated by the LLM (excluding reasoning tokens)
    reasoning_tokens: int | None = None  # Output tokens attributed to reasoning effort, if supported by the model

    @classmethod
    def from_usage(cls, usage: dict[str, Any]) -> TokenUsageMetrics:
        """Create TokenUsageMetrics from a usage dictionary returned by the LLM provider."""
        input_tokens = _safe_int(usage.get('input_tokens'))
        output_tokens = _safe_int(usage.get('output_tokens'))
        cached_tokens = _safe_int(usage.get('input_tokens_details', {}).get('cached_tokens'))
        reasoning_tokens = _safe_int(usage.get('output_tokens_details', {}).get('reasoning_tokens'))
        if input_tokens is not None and cached_tokens is not None:
            input_tokens -= cached_tokens  # Exclude cached tokens from input token count
        if output_tokens is not None and reasoning_tokens is not None:
            output_tokens -= reasoning_tokens  # Exclude reasoning tokens from output token count
        return TokenUsageMetrics(
            input_tokens=max(input_tokens, 0) if input_tokens is not None else None,
            output_tokens=max(output_tokens, 0) if output_tokens is not None else None,
            cached_tokens=max(cached_tokens, 0) if cached_tokens is not None else None,
            reasoning_tokens=max(reasoning_tokens, 0) if reasoning_tokens is not None else None,
        )


@dataclass(frozen=True)
class EntityExtractionMetrics:
    """Relevant entity extraction metrics."""

    source_status_counts: dict[ExtractionStatus, int]
    job_status_counts: dict[JobStatus, int]
    last_job_status_counts: dict[JobStatus, int]
    job_status_duration: dict[JobStatus, JobDurationMetrics]
    entity_count: int
    entity_mentions: int
    token_usage: dict[JobStatus, TokenUsageMetrics]
    elapsed_time: float | None = None  # Elapsed time since the last metrics logging tick, in seconds
    last_smoothed_job_resolution_rate: float | None = None

    # Progress

    @property
    def total_sources(self) -> int:
        """Total number of sources."""
        return int(sum(self.source_status_counts.values()))

    @property
    def source_counts(self) -> dict[str, int]:
        """Source counts grouped by status."""
        return {
            'pending': self.source_status_counts.get(ExtractionStatus.PENDING, 0),
            'in_progress': self.source_status_counts.get(ExtractionStatus.IN_PROGRESS, 0),
            'retry': self.source_status_counts.get(ExtractionStatus.RETRY, 0),
            'completed': self.source_status_counts.get(ExtractionStatus.COMPLETED, 0),
            'failed': self.source_status_counts.get(ExtractionStatus.FAILED, 0),
        }

    @property
    def source_percentages(self) -> dict[str, float]:
        """Source percentages grouped by status."""
        total_sources = self.total_sources
        return {
            'pending': (self.source_counts['pending'] / total_sources) * 100 if total_sources > 0 else 0.0,
            'in_progress': (self.source_counts['in_progress'] / total_sources) * 100 if total_sources > 0 else 0.0,
            'retry': (self.source_counts['retry'] / total_sources) * 100 if total_sources > 0 else 0.0,
            'completed': (self.source_counts['completed'] / total_sources) * 100 if total_sources > 0 else 0.0,
            'failed': (self.source_counts['failed'] / total_sources) * 100 if total_sources > 0 else 0.0,
        }

    @property
    def remaining_sources(self) -> int:
        """Remaining sources to process."""
        return self.source_counts['pending'] + self.source_counts['in_progress'] + self.source_counts['retry']

    @property
    def estimated_completion_time(self) -> float:
        """Estimated time to complete remaining sources, in hours."""
        throughput = self.smoothed_job_resolution_rate  # Jobs resolved per minute
        remaining_jobs = self.remaining_sources  # Ideal number of jobs remaining to process all sources
        if throughput > 0:
            estimated_minutes = remaining_jobs / throughput
            return estimated_minutes / 60  # Convert minutes to hours
        return float('inf')  # Infinite time if throughput is zero or undefined

    # Execution

    @property
    def total_jobs(self) -> int:
        """Total number of jobs."""
        return int(sum(self.job_status_counts.values()))

    @property
    def job_counts(self) -> dict[str, int]:
        """Job counts grouped by status."""
        return {
            'in_progress': self.job_status_counts.get(JobStatus.IN_PROGRESS, 0),
            'completed': self.job_status_counts.get(JobStatus.COMPLETED, 0),
            'failed': self.job_status_counts.get(JobStatus.FAILED, 0),
        }

    @property
    def job_percentages(self) -> dict[str, float]:
        """Job percentages grouped by status."""
        total_jobs = self.total_jobs
        return {
            'in_progress': (self.job_counts['in_progress'] / total_jobs) * 100 if total_jobs > 0 else 0.0,
            'completed': (self.job_counts['completed'] / total_jobs) * 100 if total_jobs > 0 else 0.0,
            'failed': (self.job_counts['failed'] / total_jobs) * 100 if total_jobs > 0 else 0.0,
        }

    @property
    def job_resolution_rate(self) -> float:
        """Job resolution rate, in jobs per minute."""
        if self.elapsed_time is None or self.elapsed_time <= 0:
            return 0.0
        resolved_jobs = self.job_counts['completed'] + self.job_counts['failed']
        last_resolved_jobs = self.last_job_status_counts.get(JobStatus.COMPLETED, 0) + self.last_job_status_counts.get(
            JobStatus.FAILED,
            0,
        )
        resolution_delta = resolved_jobs - last_resolved_jobs
        return (resolution_delta / self.elapsed_time) * 60  # Convert to jobs per minute

    @property
    def smoothed_job_resolution_rate(self) -> float:
        """Smoothed job resolution rate, in jobs per minute."""
        if self.last_smoothed_job_resolution_rate is None:
            return self.job_resolution_rate

        # Apply exponential smoothing with an alpha factor
        alpha = 0.3
        return alpha * self.job_resolution_rate + (1 - alpha) * self.last_smoothed_job_resolution_rate

    @property
    def job_completion_rate(self) -> float:
        """Job completion rate, in jobs per minute."""
        if self.elapsed_time is None or self.elapsed_time <= 0:
            return 0.0
        completed_jobs = self.job_counts['completed']
        last_completed_jobs = self.last_job_status_counts.get(JobStatus.COMPLETED, 0)
        completion_delta = completed_jobs - last_completed_jobs
        return (completion_delta / self.elapsed_time) * 60  # Convert to jobs per minute

    @property
    def job_throughput(self) -> dict[str, float]:
        """Job throughput metrics, in jobs per minute."""
        return {'resolution': self.job_resolution_rate, 'completion': self.job_completion_rate}

    @property
    def job_duration(self) -> dict[str, float]:
        """Job duration metrics across all finished jobs, in seconds."""
        finished_jobs = self.job_counts['completed'] + self.job_counts['failed']
        finished_job_durations = {
            status: duration
            for status, duration in self.job_status_duration.items()
            if status in {JobStatus.COMPLETED, JobStatus.FAILED} and self.job_status_counts.get(status, 0)
        }
        avg_duration = (
            sum(
                duration.avg * self.job_status_counts.get(status, 0)
                for status, duration in finished_job_durations.items()
            )
            / finished_jobs
            if finished_jobs > 0
            else 0.0
        )
        min_duration = min((duration.min for duration in finished_job_durations.values()), default=0)
        max_duration = max((duration.max for duration in finished_job_durations.values()), default=0)

        # Convert milliseconds to seconds
        return {
            'avg': avg_duration / 1000,
            'min': min_duration / 1000,
            'max': max_duration / 1000,
        }

    # Output

    @property
    def mentions_per_entity(self) -> float:
        """Average number of mentions per unique entity."""
        return self.entity_mentions / self.entity_count if self.entity_count > 0 else 0.0

    @property
    def entities_per_source(self) -> float:
        """Average number of unique entities per completed source."""
        completed_sources = self.source_counts['completed']
        return self.entity_count / completed_sources if completed_sources > 0 else 0.0

    @property
    def mentions_per_source(self) -> float:
        """Average number of entity mentions per completed source."""
        completed_sources = self.source_counts['completed']
        return self.entity_mentions / completed_sources if completed_sources > 0 else 0.0

    # Tokens

    @property
    def token_counts(self) -> dict[str, int]:
        """Token counts across all jobs grouped by token category."""
        return {
            'input': sum(metrics.input_tokens or 0 for metrics in self.token_usage.values()),
            'cached': sum(metrics.cached_tokens or 0 for metrics in self.token_usage.values()),
            'output': sum(metrics.output_tokens or 0 for metrics in self.token_usage.values()),
            'reasoning': sum(metrics.reasoning_tokens or 0 for metrics in self.token_usage.values()),
        }

    @property
    def average_token_counts(self) -> dict[str, int]:
        """Average token counts per completed job."""
        completed_token_counts = self.token_usage.get(JobStatus.COMPLETED, TokenUsageMetrics(0, 0, 0, 0))
        completed_jobs = self.job_counts['completed']
        return {
            'input': int((completed_token_counts.input_tokens or 0) / completed_jobs) if completed_jobs > 0 else 0,
            'cached': int((completed_token_counts.cached_tokens or 0) / completed_jobs) if completed_jobs > 0 else 0,
            'output': int((completed_token_counts.output_tokens or 0) / completed_jobs) if completed_jobs > 0 else 0,
            'reasoning': int((completed_token_counts.reasoning_tokens or 0) / completed_jobs)
            if completed_jobs > 0
            else 0,
        }


@dataclass(frozen=True)
class ExtractionMetricsState:
    """State of the extraction metrics at a given point during execution."""

    # Timestamp for the last metrics emission
    last_metrics_at: float | None = None

    # Number of jobs at the last metrics emission, grouped by status
    last_job_status_counts: dict[JobStatus, int] = field(default_factory=dict)

    # Smoothed rate of job resolution (jobs per minute)
    smoothed_resolution_rate: float | None = None
