### Project ###

[project]
name = "wukong-engine"
version = "0.1.0"
description = "Engine for constructing knowledge graphs from unstructured documents, using the power of LLMs."
readme = "README.md"
requires-python = ">=3.13"
license = "Proprietary"
authors = [{ name = "BFFV" }]
dependencies = [
    "nltk (>=3.9.1,<4.0.0)",
    "python-dotenv (>=1.1.0,<2.0.0)",
    "openai (>=1.88.0,<2.0.0)",
    "semantic-text-splitter (>=0.27.0,<0.28.0)",
    "datasketch (>=1.6.5,<2.0.0)",
    "fuzzywuzzy (>=0.18.0,<0.19.0)",
    "unidecode (>=1.4.0,<2.0.0)",
    "levenshtein (>=0.27.1,<0.28.0)",
]

[project.urls]
repository = "https://github.com/MillenniumDB/wukong-engine"

### Packaging ###

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{ include = "wukong_engine", from = "src" }]

[tool.setuptools.packages.find]
where = ["src"]
include = ["wukong_engine"]

### Development ###

[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = ["ALL"] # Select all rules as a base
extend-select = [
    "D401", # Require imperative mood for first line in docstrings
    "D404", # First line in docstrings should not start with "This"
]
ignore = [
    "E501",   # Ignore long lines that cannot be auto-formatted
    "ANN401", # Allow ANY for type hints
    "G004",   # Allow f-strings on logging messages
    "EM101",  # Allow strings on exception messages
    "EM102",  # Allow f-strings on exception messages
    "TRY003", # Allow long custom exception messages
    "TRY400", # Allow logging exceptions without a traceback
    "TD003",  # Allow TODO comments without an issue link
]
unfixable = ["F401"] # Do not auto-fix unused imports

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "double"

[tool.ruff.lint.mccabe]
max-complexity = 30

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pylint]
max-branches = 30
max-statements = 75

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
docstring-code-format = false

[tool.pyright]
typeCheckingMode = "basic"
reportAssertAlwaysTrue = false
reportDuplicateImport = false
reportPrivateUsage = false
reportRedeclaration = false
reportShadowedImports = false
reportUndefinedVariable = false
reportUnnecessaryCast = false
reportUnsupportedDunderAll = false
reportUnusedExpression = false
reportUnusedImport = false
reportUnusedVariable = false
reportWildcardImportFromLibrary = false
