"""Response model for LLM interactions."""

from dataclasses import dataclass
from typing import Any

from wukong_engine.app.llm.model.values import LLMProvider


@dataclass(frozen=True, slots=True)
class LLMResponse:
    """Response envelope returned by an LLM client.

    Attributes:
        content: Text content generated by the LLM.
        model: Name of the model that generated the response, as reported by the provider.
        metrics: Provider-reported usage metrics (e.g. token counts); empty if none were reported.
    """

    content: str
    model: str
    metrics: dict[str, Any]


@dataclass(frozen=True, slots=True)
class LLMBatchCreationResponse:
    """Response envelope returned by an LLM client for batch creation.

    Attributes:
        batch_id: Provider identifier of the created batch.
        provider: Provider the batch was created with.
    """

    batch_id: str
    provider: LLMProvider


@dataclass(frozen=True, slots=True)
class LLMBatchResult:
    """Response envelope returned by an LLM client for individual batch results.

    Attributes:
        job_id: Identifier of the job the result belongs to.
        response: LLM response for the job, or None if the request failed.
        error: Error message if the request failed, or None if it succeeded.
    """

    job_id: str
    response: LLMResponse | None
    error: str | None = None
