"""Metrics from LLM interactions."""

from dataclasses import dataclass
from typing import Any


def safe_int(value: Any) -> int | None:
    """Safely convert a value to an integer, returning None if conversion fails."""
    try:
        return int(value)
    except ValueError, TypeError:
        return None


@dataclass(frozen=True)
class LLMResponseMetrics:
    """Response metrics returned by an LLM client."""

    input_tokens: int | None = None  # Input tokens, excluding cached tokens if applicable
    cached_tokens: int | None = None  # Input tokens that used prefix caching
    output_tokens: int | None = None  # Output tokens generated by the LLM (excluding reasoning tokens)
    reasoning_tokens: int | None = None  # Output tokens attributed to reasoning effort, if supported by the model

    @classmethod
    def from_usage(cls, usage: dict[str, Any]) -> LLMResponseMetrics:
        """Create LLMResponseMetrics from a usage dictionary returned by the LLM provider."""
        input_tokens = safe_int(usage.get('input_tokens'))
        output_tokens = safe_int(usage.get('output_tokens'))
        cached_tokens = safe_int(usage.get('input_tokens_details', {}).get('cached_tokens'))
        reasoning_tokens = safe_int(usage.get('output_tokens_details', {}).get('reasoning_tokens'))
        if input_tokens is not None and cached_tokens is not None:
            input_tokens -= cached_tokens  # Exclude cached tokens from input token count
        if output_tokens is not None and reasoning_tokens is not None:
            output_tokens -= reasoning_tokens  # Exclude reasoning tokens from output token count
        return LLMResponseMetrics(
            input_tokens=max(input_tokens, 0) if input_tokens is not None else None,
            output_tokens=max(output_tokens, 0) if output_tokens is not None else None,
            cached_tokens=max(cached_tokens, 0) if cached_tokens is not None else None,
            reasoning_tokens=max(reasoning_tokens, 0) if reasoning_tokens is not None else None,
        )
