"""Metrics from LLM interactions."""

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class LLMResponseMetrics:
    """Response metrics returned by an LLM client."""

    input_tokens: int | None = None  # Total input tokens, including cached tokens if applicable
    output_tokens: int | None = None  # Total output tokens generated by the LLM
    cached_tokens: int | None = None  # Input tokens that used caching
    reasoning_tokens: int | None = None  # Output tokens attributed to reasoning effort, if supported by the model

    @classmethod
    def from_usage(cls, usage: dict[str, Any]) -> LLMResponseMetrics:
        """Create LLMResponseMetrics from a usage dictionary returned by the LLM provider."""
        return LLMResponseMetrics(
            input_tokens=usage.get('input_tokens'),
            output_tokens=usage.get('output_tokens'),
            cached_tokens=usage.get('input_tokens_details', {}).get('cached_tokens'),
            reasoning_tokens=usage.get('output_tokens_details', {}).get('reasoning_tokens'),
        )
